#!/usr/bin/env ruby

=begin
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
=end


total = 2
f0 = 1
f1 = 2
f = f0 + f1

while f < 4000000
  total += f if f % 2 == 0

  f0 = f1
  f1 = f
  f = f0 + f1
end

puts "ANSWER: #{total}"
t = Benchmark.ms do
(1..32).inject([0, 1]) { |a, i| (a << a[-1] + a[-2] if a[-1] + a[-2] <= 4000000) || a }.reject(&:odd?).sum
end
